### PR TITLE
gems: bump dependencies

### PR DESCRIPTION
**Pull request by q9f**
- replaces `eth-patched` with `eth` (reverts #165) - I'm co-maintainer now
- replaces `digest-sha3` (unmaintained) with `keccak` - I'm maintaining that one too
- adds `ffi` (couldn't get `rspec` to work without)
- bumped `rake` to 13.0
- bumped some minor versions

### CODE REVIEW

**Comment by justinsoong** [comment]
👍

**Comment by q9f** [comment]
bump `keccak` to 1.3.0; rename `::SHA3` to `::Keccak`
* ref https://github.com/q9f/keccak.rb/pull/16

**Comment by w4ll3** [comment]
Can this be merged? I can't use this gem right now because of the `digest-sha3` dependency.

**Comment by jovanmaric** [comment]
@kurotaky can this be merged?

**Comment by q9f** [comment]
I started importing ABI into `eth` if this is of relevance for any of you.

https://github.com/q9f/eth.rb/pull/29

**Review by kurotaky — APPROVED** [review]
Thanks!

**Comment by q9f** [comment]
@kurotaky do you plan to continue working on ethereum.rb or shall we merge the gems with https://github.com/q9f/eth.rb

Would you be interested to contribute? We have a Ruby Ethereum group on Telegram to coordinate.

**Comment by empeje** [comment]
Hi @q9f I'm both Ruby and Eth developer, looking for good quality eth client as well. I recently encounter issue when installing ethereum.rb, would lke to contribute as well. Can I get invited to the Ruby Ethereum group?

**Comment by q9f** [comment]
> Hi @q9f I'm both Ruby and Eth developer, looking for good quality eth client as well. I recently encounter issue when installing ethereum.rb, would lke to contribute as well. Can I get invited to the Ruby Ethereum group?

Yes, sure! The group is public for anyone interested! https://t.me/ruby_eth

**Comment by empeje** [comment]
Thanks @q9f

**Comment by kurotaky** [comment]
@q9f I'm not currently using ethereum.rb myself, so it might be better to have users switch to eth.rb.
ethereum.rb may continue to support Eth1 only. Anyway, I joined the Ruby Ethereum group!

**Pull request merged**
