### PR TITLE
don't limit whitespace before and after contract json abi delimiter

### PR DESCRIPTION
**Pull request by dfherr**
I got errors compiling contracts with 

```
$ solc --version
solc, the solidity compiler commandline interface
Version: 0.4.13+commit.0fb4cb1a.Linux.g++
```

because the whitespace for and after CONTRACT JSON ABI was too strict. This PR fixes this issue.

### CODE REVIEW

**Comment by dfherr** [comment]
this PR also fixes your failing specs :)

**Comment by dfherr** [comment]
i also fixed the errors resulting in party's net_version call returning decimal and not hex.

**Comment by marekkirejczyk** [comment]
@dfherr Some great, great work! Thank you.

**Comment by marekkirejczyk** [comment]
Important fixes, released new version :)

**Pull request merged**
