### PR TITLE
Added new functional

### PR DESCRIPTION
**Pull request by artamonovdev**
1) Possibility adding state of the request. By default state is latest. User can set other state for example pending, latest...

2) Added new function "send_raw_command". This function very useful when user want send the raw command using this client.

### CODE REVIEW

**Comment by marekkirejczyk** [comment]
hi  @artamonovdev 
Thank you for PR!
I added proposition for improvements in the code. Would be great if you can apply them and I'll be happy to merge.

**Comment by artamonovdev** [comment]
Why you don't want merge this pull-request?

**Comment by marekkirejczyk** [comment]
@artamonovdev, I was hoping you will implement changes proposed in comments first.

**Comment by artamonovdev** [comment]
@marekkirejczyk I what to know the pending balance of a wallet. But with this library I can find out only "latest" balance of a wallet.

**Pull request closed without merging**
